/**
 * Obsidian session-log manifest loader.
 *
 * The manifest is generated by a separate script and committed under
 * docs/obsidian/_manifest.json. We read it on the server at request time so
 * that a new session log appears on next navigation without a rebuild.
 */

import "server-only";

import fs from "node:fs/promises";
import path from "node:path";
import { OBSIDIAN_DIR } from "./markdown";

export type LogEntry = {
  file: string;           // "2026-04-14-01-WhaleScope-진행내역.md"
  date: string | null;    // "2026-04-14" | null
  seq: string;            // "01" | ""
  title: string;          // "WhaleScope (02015) — 진행내역"
  slug: string;           // "WhaleScope-진행내역"
  category: string;       // "project-progress" | "UX · 디자인" | ...
  // "obsidian" (default) → docs/obsidian/<file>
  // "dashboard"          → apps/dashboard/<file>  (설계 문서 등)
  source?: "obsidian" | "dashboard";
};

export type LogManifest = {
  generated_at: string;
  count: number;
  entries: LogEntry[];
};

export async function loadLogManifest(): Promise<LogManifest> {
  const manifestPath = path.join(OBSIDIAN_DIR, "_manifest.json");
  try {
    const raw = await fs.readFile(manifestPath, "utf8");
    const parsed = JSON.parse(raw) as unknown;
    if (
      parsed &&
      typeof parsed === "object" &&
      Array.isArray((parsed as LogManifest).entries)
    ) {
      return parsed as LogManifest;
    }
    return { generated_at: "", count: 0, entries: [] };
  } catch {
    return { generated_at: "", count: 0, entries: [] };
  }
}
