"""Storage Protocol. Full signatures filled in TRACK 2; SheetsClient implements via duck typing."""
from __future__ import annotations

from typing import Protocol


class Storage(Protocol):
    # Legacy methods (already implemented in SheetsClient)
    def append_transactions(self, rows: list[dict]) -> int: ...
    def save_daily_brief(self, row: dict) -> None: ...
    def log_run(self, row: dict) -> None: ...
    def add_subscriber(self, chat_id: int, username: str | None) -> bool: ...
    def get_active_subscribers(self) -> list[dict]: ...

    # New tabs (TRACK 2)
    def upsert_watched_address(self, addr: dict) -> None: ...
    def list_watched_addresses(self) -> dict[str, dict]: ...
    def append_address_activity(self, events: list[dict]) -> int: ...
    def append_tg_whale_event(self, event: dict) -> None: ...
    def append_signal(self, signal: dict) -> None: ...
    def save_weekly_trend(self, rows: list[dict]) -> None: ...
    def save_analysis_log(self, entry: dict) -> None: ...
    def get_cached_analysis(self, prompt_hash: str) -> dict | None: ...
    def upsert_user_interest(
        self,
        chat_id: int,
        dimension: str,
        value: str,
        weight: float,
        source: str,
    ) -> None: ...
    def list_user_interests(self, user_id: str | None = None) -> list[dict]: ...
