"""Storage Protocol. Full signatures filled in TRACK 2; SheetsClient implements via duck typing."""
from __future__ import annotations

from datetime import datetime
from typing import Protocol


class Storage(Protocol):
    # Legacy methods (already implemented in SheetsClient)
    def append_transactions(self, rows: list[dict]) -> int: ...
    def save_daily_brief(self, row: dict) -> None: ...
    def log_run(self, row: dict) -> None: ...
    def add_subscriber(self, chat_id: int, username: str | None) -> bool: ...
    def list_subscribers(self, statuses: list[str] | None = None) -> list[dict]: ...
    def get_active_subscribers(self) -> list[dict]: ...
    def update_subscriber_language(self, chat_id: int, language: str) -> None: ...
    def append_system_log(self, level: str, category: str, payload: dict) -> None: ...
    def append_broadcast_log(self, entry: dict) -> None: ...
    def list_broadcast_log(
        self,
        *,
        kind: str | None = None,
        since: datetime | None = None,
        limit: int | None = None,
    ) -> list[dict]: ...
    def append_llm_budget_log(self, entry: dict) -> None: ...
    def list_llm_budget_log(
        self,
        month_key: str | None = None,
        limit: int | None = None,
    ) -> list[dict]: ...
    def append_brief_cost_ledger(self, entry: dict) -> None: ...
    def list_brief_cost_ledger(
        self,
        since: datetime | None = None,
        limit: int | None = None,
    ) -> list[dict]: ...

    # New tabs (TRACK 2)
    def upsert_watched_address(self, addr: dict) -> None: ...
    def list_watched_addresses(self) -> dict[str, dict]: ...
    def append_address_activity(self, events: list[dict]) -> int: ...
    def list_address_activity(self, since=None) -> list[dict]: ...
    def append_tg_whale_event(self, event: dict) -> None: ...
    def list_tg_whale_events(
        self,
        since: datetime | None = None,
        limit: int | None = None,
    ) -> list[dict[str, object]]:
        """Return TG whale events newer than ``since``, optionally capped.

        Args:
            since: Lower bound (inclusive) on ``collected_at``. ``None`` returns all rows.
            limit: Row-count cap applied AFTER the since filter.

                * ``None`` (default): no cap -- return every matching row.
                * ``0``:              return an empty list explicitly.
                * ``> 0``:            return the last ``limit`` matching rows (tail slice).

        Returns:
            List of dict rows. Empty list when no data or sheet is missing.
        """
        ...
    def append_signal(self, signal: dict) -> None: ...
    def save_weekly_trend(self, rows: list[dict]) -> None: ...
    def save_analysis_log(self, entry: dict) -> None: ...
    def get_cached_analysis(self, prompt_hash: str) -> dict | None: ...
    def upsert_user_interest(
        self,
        chat_id: int,
        dimension: str,
        value: str,
        weight: float,
        source: str,
    ) -> None: ...
    def list_user_interests(self, user_id: str | None = None) -> list[dict]: ...
